services:
  documelt:
    container_name: documelt
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "8080:8080"
    command: ["tail", "-f", "/dev/null"]
